### ISSUE TITLE
Problem with haversine()?

### ISSUE THREAD

**Issue by caspar** [actuallyaswin/mappr#5]
```
$ python3 mappr.py
2019-04-28 23:15:49,667 - INFO - Initializing figure...
2019-04-28 23:15:49,762 - INFO - Creating a Basemap object...
2019-04-28 23:15:52,440 - INFO - Defining Basemap bounds...
2019-04-28 23:15:52,440 - INFO - Creating a legend...
2019-04-28 23:15:52,442 - INFO - Importing place data...
2019-04-28 23:15:52,444 - INFO - Importing location data...
Traceback (most recent call last):
  File "mappr.py", line 127, in <module>
    _nearest = min(data_places, key=lambda _x:
  File "mappr.py", line 128, in <lambda>
    haversine((_x['lat'], _x['lon']), _coordinate, miles=True))
TypeError: haversine() got an unexpected keyword argument 'miles'
```

**Comment by actuallyaswin** [comment]
My bad for answering this question a year and a half too late! The latest version of the `haversine` plugin uses a different call signature now, it looks like.

You'll need to replace `miles=True` with `unit='mi'` at every line where I use the _haversine_ function. I just updated the master branch here, hopefully that fixes everything for ya. 😄
